Flowpack:
  FullPageCache:
    enabled: true
Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            requestInterceptor:
              position: 'start 999999'
              component: 'Flowpack\FullPageCache\Http\RequestInterceptorComponent'
            addCacheHeader:
              position: 'after setHeader'
              component: 'Flowpack\FullPageCache\Http\CacheControlHeaderComponent'
        'postprocess':
          chain:
            requestStorage:
              position: 'after standardsCompliance'
              component: 'Flowpack\FullPageCache\Http\RequestStorageComponent'
