Flowpack:
  FullPageCache:
    # enable full page caching
    enabled: true

    # the maximum public cache control header sent
    # set to 0 if you do not want to send public CacheControl headers
    maxPublicCacheTime: 86400

    # requests that include query arguments won't be cached by default to prevent unexpected caching behaviour
    # however, if you know what you are doing, use these settings to enable cached results for query arguments
    # if the request uri still has arguments that are not listed in 'include' or 'ignore', the default no-cache behaviour will apply
    queryArguments:

      # list of arguments that should response cached results
      # thus we will *include* these arguments when we create and/or lookup the cache keys
      include: []

      # list of arguments that should be ignored (typically arguments that won't change the rendered html)
      # thus we will *ignore* these arguments when we create and/or lookup the cache keys
      ignore: []
Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            requestInterceptor:
              position: 'start 999999'
              component: 'Flowpack\FullPageCache\Http\RequestInterceptorComponent'
            addCacheHeader:
              position: 'after setHeader'
              component: 'Flowpack\FullPageCache\Http\CacheControlHeaderComponent'
        'postprocess':
          chain:
            requestStorage:
              position: 'after standardsCompliance'
              component: 'Flowpack\FullPageCache\Http\RequestStorageComponent'
