Flowpack:
  FullPageCache:
    # enable full page caching
    enabled: true

    # the maximum public cache control header sent
    # set to 0 if you do not want to send public CacheControl headers
    maxPublicCacheTime: 86400

    # requests have to fulfill certain conditions for beeing cached
    request:
      # !!! Only the http methods "GET" and "HEAD" are supported !!!

      # a request will only qualify for caching if it contains no cookieParams that
      # are not ignored.
      cookieParams:
        # ignored cookie params exclude cookies that are handled by the frontend
        # and are not relevant for the backend. A usecase would be gdpr consent cookies
        # if they are only used on the client side
        ignore: []

      # a request will only qualify for caching if it only contains queryParams that
      # are allowed or ignored. All other arguments will prevent caching.
      queryParams:
        # allowed params become part of the cache identifier, use this for
        # arguments that modify the reponse but still allow caching like pagination
        allow: []

        # ignored arguments are not part of the cache identifier but do not
        # prevent caching either. Use this for arguments that are meaningless for
        # the backend like utm_campaign
        ignore: []

Neos:
  Flow:
    http:
      middlewares:
        'fullPageRequestCache':
          middleware: 'Flowpack\FullPageCache\Middleware\RequestCacheMiddleware'
          position: 'after trustedProxies'
        'fullPagePublicCacheHeader':
          middleware: 'Flowpack\FullPageCache\Middleware\PublicCacheHeaderMiddleware'
          position: 'before fullPageCacheHeader'
        'fullPageCacheHeader':
          middleware: 'Flowpack\FullPageCache\Middleware\CacheHeaderMiddleware'
          position: 'after fullPageRequestCache'
