name: PHP Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: "Test (PHP ${{ matrix.php-versions }}, Neos ${{ matrix.neos-versions }})"

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3']
        neos-versions: ['8.3']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Set Neos Version
        run: composer require neos/neos ^${{ matrix.neos-versions }} --no-progress --no-interaction

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer test
